"""
Complete world language list — ISO 639-1 + major regional variants.
Format: { "code": IETF BCP 47 tag, "name": English name, "nativeName": name in that language }
"""

WORLD_LANGUAGES = [
    {"code": "en-US", "name": "English (United States)", "nativeName": "English"},
    {"code": "en-GB", "name": "English (United Kingdom)", "nativeName": "English"},
    {"code": "en-AU", "name": "English (Australia)", "nativeName": "English"},
    {"code": "en-CA", "name": "English (Canada)", "nativeName": "English"},
    {"code": "es-ES", "name": "Spanish (Spain)", "nativeName": "Español (España)"},
    {"code": "es-MX", "name": "Spanish (Mexico)", "nativeName": "Español (México)"},
    {"code": "es-AR", "name": "Spanish (Argentina)", "nativeName": "Español (Argentina)"},
    {"code": "es-CO", "name": "Spanish (Colombia)", "nativeName": "Español (Colombia)"},
    {"code": "fr-FR", "name": "French (France)", "nativeName": "Français (France)"},
    {"code": "fr-CA", "name": "French (Canada)", "nativeName": "Français (Canada)"},
    {"code": "fr-BE", "name": "French (Belgium)", "nativeName": "Français (Belgique)"},
    {"code": "pt-BR", "name": "Portuguese (Brazil)", "nativeName": "Português (Brasil)"},
    {"code": "pt-PT", "name": "Portuguese (Portugal)", "nativeName": "Português (Portugal)"},
    {"code": "de-DE", "name": "German (Germany)", "nativeName": "Deutsch (Deutschland)"},
    {"code": "de-AT", "name": "German (Austria)", "nativeName": "Deutsch (Österreich)"},
    {"code": "de-CH", "name": "German (Switzerland)", "nativeName": "Deutsch (Schweiz)"},
    {"code": "zh-CN", "name": "Chinese (Simplified)", "nativeName": "中文（简体）"},
    {"code": "zh-TW", "name": "Chinese (Traditional)", "nativeName": "中文（繁體）"},
    {"code": "zh-HK", "name": "Chinese (Hong Kong)", "nativeName": "中文（香港）"},
    {"code": "ja-JP", "name": "Japanese", "nativeName": "日本語"},
    {"code": "ko-KR", "name": "Korean", "nativeName": "한국어"},
    {"code": "ar-SA", "name": "Arabic (Saudi Arabia)", "nativeName": "العربية"},
    {"code": "ar-EG", "name": "Arabic (Egypt)", "nativeName": "العربية (مصر)"},
    {"code": "ar-AE", "name": "Arabic (UAE)", "nativeName": "العربية (الإمارات)"},
    {"code": "hi-IN", "name": "Hindi", "nativeName": "हिन्दी"},
    {"code": "ru-RU", "name": "Russian", "nativeName": "Русский"},
    {"code": "it-IT", "name": "Italian", "nativeName": "Italiano"},
    {"code": "nl-NL", "name": "Dutch (Netherlands)", "nativeName": "Nederlands"},
    {"code": "nl-BE", "name": "Dutch (Belgium)", "nativeName": "Nederlands (België)"},
    {"code": "pl-PL", "name": "Polish", "nativeName": "Polski"},
    {"code": "tr-TR", "name": "Turkish", "nativeName": "Türkçe"},
    {"code": "sv-SE", "name": "Swedish", "nativeName": "Svenska"},
    {"code": "da-DK", "name": "Danish", "nativeName": "Dansk"},
    {"code": "nb-NO", "name": "Norwegian (Bokmål)", "nativeName": "Norsk Bokmål"},
    {"code": "fi-FI", "name": "Finnish", "nativeName": "Suomi"},
    {"code": "el-GR", "name": "Greek", "nativeName": "Ελληνικά"},
    {"code": "cs-CZ", "name": "Czech", "nativeName": "Čeština"},
    {"code": "sk-SK", "name": "Slovak", "nativeName": "Slovenčina"},
    {"code": "hu-HU", "name": "Hungarian", "nativeName": "Magyar"},
    {"code": "ro-RO", "name": "Romanian", "nativeName": "Română"},
    {"code": "bg-BG", "name": "Bulgarian", "nativeName": "Български"},
    {"code": "hr-HR", "name": "Croatian", "nativeName": "Hrvatski"},
    {"code": "uk-UA", "name": "Ukrainian", "nativeName": "Українська"},
    {"code": "he-IL", "name": "Hebrew", "nativeName": "עברית"},
    {"code": "th-TH", "name": "Thai", "nativeName": "ไทย"},
    {"code": "vi-VN", "name": "Vietnamese", "nativeName": "Tiếng Việt"},
    {"code": "id-ID", "name": "Indonesian", "nativeName": "Bahasa Indonesia"},
    {"code": "ms-MY", "name": "Malay", "nativeName": "Bahasa Melayu"},
    {"code": "fa-IR", "name": "Persian (Farsi)", "nativeName": "فارسی"},
    {"code": "ur-PK", "name": "Urdu", "nativeName": "اردو"},
    {"code": "bn-BD", "name": "Bengali (Bangladesh)", "nativeName": "বাংলা"},
    {"code": "bn-IN", "name": "Bengali (India)", "nativeName": "বাংলা (ভারত)"},
    {"code": "ta-IN", "name": "Tamil", "nativeName": "தமிழ்"},
    {"code": "te-IN", "name": "Telugu", "nativeName": "తెలుగు"},
    {"code": "mr-IN", "name": "Marathi", "nativeName": "मराठी"},
    {"code": "gu-IN", "name": "Gujarati", "nativeName": "ગુજરાતી"},
    {"code": "kn-IN", "name": "Kannada", "nativeName": "ಕನ್ನಡ"},
    {"code": "ml-IN", "name": "Malayalam", "nativeName": "മലയാളം"},
    {"code": "pa-IN", "name": "Punjabi", "nativeName": "ਪੰਜਾਬੀ"},
    {"code": "sw-KE", "name": "Swahili", "nativeName": "Kiswahili"},
    {"code": "af-ZA", "name": "Afrikaans", "nativeName": "Afrikaans"},
    {"code": "am-ET", "name": "Amharic", "nativeName": "አማርኛ"},
    {"code": "az-AZ", "name": "Azerbaijani", "nativeName": "Azərbaycan"},
    {"code": "be-BY", "name": "Belarusian", "nativeName": "Беларуская"},
    {"code": "ca-ES", "name": "Catalan", "nativeName": "Català"},
    {"code": "et-EE", "name": "Estonian", "nativeName": "Eesti"},
    {"code": "eu-ES", "name": "Basque", "nativeName": "Euskara"},
    {"code": "gl-ES", "name": "Galician", "nativeName": "Galego"},
    {"code": "hy-AM", "name": "Armenian", "nativeName": "Հայերեն"},
    {"code": "is-IS", "name": "Icelandic", "nativeName": "Íslenska"},
    {"code": "ka-GE", "name": "Georgian", "nativeName": "ქართული"},
    {"code": "kk-KZ", "name": "Kazakh", "nativeName": "Қазақша"},
    {"code": "km-KH", "name": "Khmer", "nativeName": "ខ្មែរ"},
    {"code": "lo-LA", "name": "Lao", "nativeName": "ລາວ"},
    {"code": "lt-LT", "name": "Lithuanian", "nativeName": "Lietuvių"},
    {"code": "lv-LV", "name": "Latvian", "nativeName": "Latviešu"},
    {"code": "mk-MK", "name": "Macedonian", "nativeName": "Македонски"},
    {"code": "mn-MN", "name": "Mongolian", "nativeName": "Монгол"},
    {"code": "my-MM", "name": "Burmese", "nativeName": "မြန်မာ"},
    {"code": "ne-NP", "name": "Nepali", "nativeName": "नेपाली"},
    {"code": "si-LK", "name": "Sinhala", "nativeName": "සිංහල"},
    {"code": "sl-SI", "name": "Slovenian", "nativeName": "Slovenščina"},
    {"code": "sq-AL", "name": "Albanian", "nativeName": "Shqip"},
    {"code": "sr-RS", "name": "Serbian", "nativeName": "Српски"},
    {"code": "tl-PH", "name": "Filipino (Tagalog)", "nativeName": "Filipino"},
    {"code": "uz-UZ", "name": "Uzbek", "nativeName": "O'zbek"},
    {"code": "zu-ZA", "name": "Zulu", "nativeName": "isiZulu"},
    {"code": "cy-GB", "name": "Welsh", "nativeName": "Cymraeg"},
    {"code": "mt-MT", "name": "Maltese", "nativeName": "Malti"},
    {"code": "ga-IE", "name": "Irish", "nativeName": "Gaeilge"},
]
